
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class gerolingui5_imagenes extends javax.swing.JFrame {

    /**
     * Creates new form gerolingui5_imagenes
     */
    public gerolingui5_imagenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        HarryPotter = new javax.swing.JButton();
        LordoftheRings = new javax.swing.JButton();
        HungerGames = new javax.swing.JButton();
        Narnia = new javax.swing.JButton();
        MazeRunner = new javax.swing.JButton();
        Twilight = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel4.setText("Selecciona tu saga favorita:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setText("Lo que tu saga de fantasía favorita dice de vos...");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Selecciona tu saga favorita:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 204));
        jLabel5.setText("Edad:");

        Edad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        Nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        HarryPotter.setForeground(new java.awt.Color(255, 255, 255));
        HarryPotter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/harrypotterandthesorcerersstonemovie_Movies_harrypotterylapiedrahechiceros_8127 (1).png"))); // NOI18N
        HarryPotter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarryPotterActionPerformed(evt);
            }
        });

        LordoftheRings.setForeground(new java.awt.Color(255, 255, 255));
        LordoftheRings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/The_Lord_of_the_Rings_-_The_Fellowship_of_the_Ring_32484.png"))); // NOI18N
        LordoftheRings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LordoftheRingsActionPerformed(evt);
            }
        });

        HungerGames.setForeground(new java.awt.Color(255, 255, 255));
        HungerGames.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/The_Hunger_Games_32516.png"))); // NOI18N
        HungerGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HungerGamesActionPerformed(evt);
            }
        });

        Narnia.setBackground(new java.awt.Color(255, 255, 255));
        Narnia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/The_Chronicles_of_Narnia_-_The_Lion__the_Witch_and_the_Wardrobe_32379.png"))); // NOI18N
        Narnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NarniaActionPerformed(evt);
            }
        });

        MazeRunner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/The_Maze_Runner_33497.png"))); // NOI18N
        MazeRunner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MazeRunnerActionPerformed(evt);
            }
        });

        Twilight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Twilight_32593.png"))); // NOI18N
        Twilight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwilightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MazeRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(HungerGames, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LordoftheRings, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HarryPotter, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Twilight, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(Narnia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HarryPotter)
                    .addComponent(LordoftheRings)
                    .addComponent(Narnia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MazeRunner)
                    .addComponent(Twilight)
                    .addComponent(HungerGames))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HarryPotterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarryPotterActionPerformed
        // TODO add your handling code here:
        String nombre=Nombre.getText();
        String edad=Edad.getText();
        String harrypotter="Nombre: "+nombre+"\nEdad: "+edad+"\nTenés buen gusto y sos una persona agradable. Sin embargo, si te uniste al fandom debés ser algo insoportable."
                +"\nProbablemente, ya leíste varios o todos los libros y sabés cada dato curioso de la saga";
        JOptionPane.showMessageDialog(this,harrypotter,"Harry Potter",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_HarryPotterActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void TwilightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwilightActionPerformed
        // TODO add your handling code here:
        String nombre=Nombre.getText();
        String edad=Edad.getText();
        String twilight="Nombre: "+nombre+"\nEdad: "+edad+"\nMe atrevo a discrminar tu gusto por películas porque esta saga es malísima."
                +"\nAmás la saga porque marco tu adolescencia o porque no superás la pareja de Robert Pattinson y Kristen Stewart."
                +"\nAhora, si realmente disfrutás ver estas películas y no hay una escena que te dé cringe, considerá seriamente tu mal gusto en película.s";
        JOptionPane.showMessageDialog(this,twilight,"Twilight",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_TwilightActionPerformed

    private void LordoftheRingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LordoftheRingsActionPerformed
        // TODO add your handling code here:
        String nombre=Nombre.getText();
        String edad=Edad.getText();
        String lordoftherings="Nombre: "+nombre+"\nEdad: "+edad+"\nSabés mucho de calidad cinematográfica y tenés un gusto superior. Sos inteligente y muy observador/a."
                +"\nProbablemente te gustan las cosas extensas y duraderas en general, porque 3 horas por película es un montón.";
        JOptionPane.showMessageDialog(this,lordoftherings,"Lord Of The Rings",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_LordoftheRingsActionPerformed

    private void HungerGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HungerGamesActionPerformed
        // TODO add your handling code here:
        String nombre=Nombre.getText();
        String edad=Edad.getText();
        String hungergames="Nombre: "+nombre+"\nEdad: "+edad+"\nProbablemente te sentís identificado/a con Katniss Everdeen, te considerás un/a rebelde y querés hacer un cambio en el mundo."
                +"\nLa gente te ama o te odia, no hay punto medio.";
        JOptionPane.showMessageDialog(this,hungergames,"Hunger Games",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_HungerGamesActionPerformed

    private void NarniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NarniaActionPerformed
        // TODO add your handling code here:
        String nombre=Nombre.getText();
        String edad=Edad.getText();
        String narnia="Nombre: "+nombre+"\nEdad: "+edad+"\nSeguro tenés menos de 18 años y sos muy fan de Disney."
                +"\nTenés un gusto promedio en películas, pero en este caso no te equivocás.";
        JOptionPane.showMessageDialog(this,narnia,"Hunger Games",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_NarniaActionPerformed

    private void MazeRunnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MazeRunnerActionPerformed
        // TODO add your handling code here:
        String nombre=Nombre.getText();
        String edad=Edad.getText();
        String mazerunner="Nombre: "+nombre+"\nEdad: "+edad+"\nHay dos opciones: te encantan las películas de mundos distópicos y post-apocalípticos,"
                +"\no estas enamorado/a de Dylan O'brien y ves esta película sólo porque sale él.";
        JOptionPane.showMessageDialog(this,mazerunner,"Maze Runner",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_MazeRunnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerolingui5_imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerolingui5_imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerolingui5_imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerolingui5_imagenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gerolingui5_imagenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Edad;
    private javax.swing.JButton HarryPotter;
    private javax.swing.JButton HungerGames;
    private javax.swing.JButton LordoftheRings;
    private javax.swing.JButton MazeRunner;
    private javax.swing.JButton Narnia;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton Twilight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
