
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class gerolingui2 extends javax.swing.JFrame {

    /**
     * Creates new form gerolingui2
     */
    public gerolingui2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        Grupo1 = new javax.swing.ButtonGroup();
        Grupo2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tipodepop = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Popactual = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        Dualipa = new javax.swing.JCheckBox();
        Taylorswift = new javax.swing.JCheckBox();
        Arianagrande = new javax.swing.JCheckBox();
        Harrystyles = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        Britney = new javax.swing.JRadioButton();
        Madonna = new javax.swing.JRadioButton();
        Ladygaga = new javax.swing.JRadioButton();
        Michaeljackson = new javax.swing.JRadioButton();
        Enviar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Edad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Genero = new javax.swing.JComboBox<>();

        jCheckBox3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(102, 0, 153));
        jCheckBox3.setText("Taylor Swift");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 153));
        jLabel1.setText("ENCUESTA SOBRE EL POP");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 153));
        jLabel2.setText("Elige el tipo de pop que más escuches");

        Tipodepop.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Tipodepop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electro Pop", "Indie Pop", "Pop Latino", "Country Pop" }));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 153));
        jLabel3.setText("Del 1 al 10, ¿qué tan bueno es el pop actual?");

        Popactual.setBackground(new java.awt.Color(204, 204, 204));
        Popactual.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Popactual.setForeground(new java.awt.Color(102, 0, 204));
        Popactual.setMajorTickSpacing(1);
        Popactual.setMaximum(10);
        Popactual.setMinimum(1);
        Popactual.setPaintLabels(true);
        Popactual.setPaintTicks(true);
        Popactual.setToolTipText("");
        Popactual.setValue(0);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 153));
        jLabel6.setText("Artista conocido que más escuchas");

        Grupo2.add(Dualipa);
        Dualipa.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Dualipa.setText("Dua Lipa");

        Grupo2.add(Taylorswift);
        Taylorswift.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Taylorswift.setText("Taylor Swift");

        Grupo2.add(Arianagrande);
        Arianagrande.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Arianagrande.setText("Ariana Grande");

        Grupo2.add(Harrystyles);
        Harrystyles.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Harrystyles.setText("Harry Styles");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 153));
        jLabel7.setText("Según tu opinión, ¿quién es el artista más influyente en la historia del pop? ");

        Grupo1.add(Britney);
        Britney.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Britney.setText("Britney Spears");

        Grupo1.add(Madonna);
        Madonna.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Madonna.setText("Madonna");

        Grupo1.add(Ladygaga);
        Ladygaga.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Ladygaga.setText("Lady Gaga");

        Grupo1.add(Michaeljackson);
        Michaeljackson.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        Michaeljackson.setText("Michael Jackson");
        Michaeljackson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MichaeljacksonActionPerformed(evt);
            }
        });

        Enviar.setBackground(new java.awt.Color(204, 204, 255));
        Enviar.setFont(new java.awt.Font("Georgia", 3, 20)); // NOI18N
        Enviar.setForeground(new java.awt.Color(102, 0, 153));
        Enviar.setText("ENVIAR RESPUESTAS");
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 153));
        jLabel4.setText("¿Cuántos años tenés? (Insertar edad en nros.)");

        Edad.setBackground(new java.awt.Color(204, 204, 204));
        Edad.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 153));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 153));
        jLabel8.setText("Género");

        Genero.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        Genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "Varón", "Indefinido" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(294, 294, 294)
                        .addComponent(jLabel5))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Enviar)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(Tipodepop, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Taylorswift)
                            .addComponent(Dualipa))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Arianagrande)
                            .addComponent(Harrystyles)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Britney)
                            .addComponent(Madonna))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ladygaga)
                            .addComponent(Michaeljackson)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Popactual, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tipodepop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Popactual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dualipa)
                    .addComponent(Harrystyles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Taylorswift)
                    .addComponent(Arianagrande))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Britney)
                    .addComponent(Ladygaga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Madonna)
                    .addComponent(Michaeljackson))
                .addGap(18, 18, 18)
                .addComponent(Enviar)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        // TODO add your handling code here:
        String edad=Edad.getText();
        
        String genero=Genero.getSelectedItem().toString();
        
        String tipodepop=Tipodepop.getSelectedItem().toString();
        
        int popactual=Popactual.getValue();
        
        String artista = null;
        if (Dualipa.isSelected()){
            artista="Dua Lipa";
        }
        if (Harrystyles.isSelected()){
            artista="Harry Styles";
        }
        if (Taylorswift.isSelected()){
            artista="Taylor Swift";
        }
        if (Arianagrande.isSelected()){
            artista="Ariana Grande";
        }
        
        String influyente = null;
        if (Britney.isSelected()){
            influyente="Britney Spears";
        }
        if (Ladygaga.isSelected()){
            influyente="Lady Gaga";
        }
        if (Madonna.isSelected()){
            influyente="Madonna";
        }
        if (Michaeljackson.isSelected()){
            influyente="Michael Jackson";
        }
        
        String respuestas;
        respuestas = "Edad: "+edad+"\nGénero: "+genero+"\nTipo de Pop favorito: "+tipodepop+"\nQué tan bueno es el Pop actual: "+popactual+"\nArtista actual más escuchado: "+artista+"\nArtista más influyente del pop: "+influyente;
        JOptionPane.showMessageDialog(this,respuestas,"Encuesta sobre el Pop",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_EnviarActionPerformed

    private void MichaeljacksonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MichaeljacksonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MichaeljacksonActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gerolingui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gerolingui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gerolingui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gerolingui2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gerolingui2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Arianagrande;
    private javax.swing.JRadioButton Britney;
    private javax.swing.JCheckBox Dualipa;
    private javax.swing.JTextField Edad;
    private javax.swing.JButton Enviar;
    private javax.swing.JComboBox<String> Genero;
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.ButtonGroup Grupo2;
    private javax.swing.JCheckBox Harrystyles;
    private javax.swing.JRadioButton Ladygaga;
    private javax.swing.JRadioButton Madonna;
    private javax.swing.JRadioButton Michaeljackson;
    private javax.swing.JSlider Popactual;
    private javax.swing.JCheckBox Taylorswift;
    private javax.swing.JComboBox<String> Tipodepop;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
